#!/bin/bash

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
  echo "Error: PYFILE environment variable not set."
  exit 1
fi

# Check if the PYFILE file exists
if [ ! -f "$PYFILE" ]; then
  echo "Error: File $PYFILE not found."
  exit 1
fi

# Extract the file name without extension
BASENAME=$(basename -- "$PYFILE")
FILENAME_NOEXT="${BASENAME%.*}"

# Compile the Python script to .pyc file
python -m py_compile "$PYFILE"

# Rename the compiled file to have the extension .pyc
mv "__pycache__/$FILENAME_NOEXT.cpython-*.pyc" "${FILENAME_NOEXT}c.pyc"

# Clean up the __pycache__ directory
rm -r "__pycache__"

echo "Compiling $PYFILE ..."
